In [ ]:
!pip install gym



     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 6.6 MB/s eta 0:00:00


In [ ]:
!pip install IPython

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output , display


In [ ]:
env=gym.make("FrozenLake-v1")

In [ ]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
print("Action space size:", action_space_size)
print("State space size:", state_space_size)

Action space size: 4
State space size: 16


In [ ]:
q_table = np.zeros((state_space_size, action_space_size))
print("Initial Q-table:\n", q_table)

Initial Q-table:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
num_episodes = 10000
max_steps_per_episode = 1000
learning_rate = 0.01  # alpha
discount_rate = 0.99  # gamma

exploration_rate = 1  # epsilon greedy strategy
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [ ]:

rewards_all_episodes = []

# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()

        # Take the action and observe the outcome
        new_state, reward, done, info = env.step(action)

        # Update the Q-table using the Q-learning formula
        q_table[state, action] = (1 - learning_rate) * q_table[state, action] + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        # Transition to the new state
        state = new_state

        # Accumulate the reward
        rewards_current_episode += reward

        if done:
            break

    # Decay the exploration rate
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    # Append the reward of the current episode
    rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes / 1000)
count = 1000
print("Average reward per thousand episodes:\n")

for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r) / 1000))
    count += 1000

# Display the final Q-table
print("\n\n*****Final Q-table:*****\n")
print(q_table)



Average reward per thousand episodes:

1000 :  0.052
2000 :  0.202
3000 :  0.426
4000 :  0.591
5000 :  0.639
6000 :  0.649
7000 :  0.664
8000 :  0.679
9000 :  0.723
10000 :  0.703


*****Final Q-table:*****

[[0.54987812 0.5303682  0.5287934  0.52505287]
 [0.3427384  0.35110192 0.3147646  0.50726989]
 [0.45008437 0.44656607 0.43277255 0.47584417]
 [0.3110163  0.29845552 0.33013422 0.4633339 ]
 [0.56983995 0.34832921 0.38300967 0.38008971]
 [0.         0.         0.         0.        ]
 [0.34856684 0.21231654 0.32126744 0.21107185]
 [0.         0.         0.         0.        ]
 [0.39736155 0.42235494 0.39899511 0.60442549]
 [0.43757169 0.65129189 0.42753814 0.37953765]
 [0.6254007  0.4943433  0.37990888 0.32581623]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.46193058 0.49354198 0.75645744 0.50663252]
 [0.74529457 0.8746846  0.81275341 0.7792248 ]
 [0.         0.         0.         0.        ]]


In [ ]:
for episode in range(3):
    state = env.reset()
    done = False
    print("****CHAPTER", episode + 1, "******\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        print(env.render(mode='ansi'))  # Render the environment in 'ansi' mode for text output
        time.sleep(0.3)

        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)

        state = new_state  # Update the state to the new state

        if done:
            clear_output(wait=True)
            print(env.render(mode='ansi'))
            if reward == 1:
                print("SUCCESS !!")
                time.sleep(3)
            else:
                print("FAILURE !!")
                time.sleep(3)
            clear_output(wait=True)
            break

            state = new_state

env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG

FAILURE !!
